### PR TITLE
Get correct spawn level

### PR DESCRIPTION
**Pull request by duane-r**
I think this is all you need for reasonable spawns. However, I haven't tested it thoroughly. Use it at your discretion. (And my formatting is off, obviously.)

### CODE REVIEW

**Comment by duane-r** [comment]
Actually, it works even better when you don't limit the height so much, but Paramat prefers to keep spawns lower, to put them closer to water. The trouble is, I've found a few seeds here where that fails because the terrain is uniformly high.

(Exciting spawn point!)
t

**Comment by vlapsley** [comment]
Wow Duane, you are a top bloke. I've tested the spawn code and it seems to be working with no issues. Fix the formatting and I'll merge. At least players can spawn on ground level, instead of in it.

I've still seen some seeds where the 'normal' ground level is between 100-200 nodes high, when it should be closer to y=25. See seed 17859926665365692338
image

It seems to happen on seeds where the spawn is located where two mountain types meet. noise_terrain1, 2, 3 determine where the mountains are placed.

What do you think about checking for those values being below a certain threshold to prevent spawn in absurdly high mountain ranges?

I'll sleep on it and test some more later. Thanks again mate!

**Comment by duane-r** [comment]
> What do you think about checking for those values being below a certain threshold to prevent spawn in absurdly high mountain ranges?

If I understand you, it's already doing that. It won't spawn you over 29 altitude. The screenshot was from when I tried removing the limit.

The problem is, the game will only try a few thousand random locations, and they all tend to be in the same area. If there's no place to be found, you just spawn underground. It expects your mapgen to produce low spots everywhere, and this one seems to have some extreme seeds that don't.

**Comment by vlapsley** [comment]
Nope that didn't work. It fixed one problem seed, but busted ones I know were previously good.

Setting the offset to 0 has the polar opposite effect on good/bad seeds compared to a value of 1.

I'm guessing it has something to do with the terrain_scale = 128 setting.

**Pull request merged**
